### ISSUE TITLE
Toolchain spawns too many Zig processes

### ISSUE THREAD

**Issue by purkhusid** [uber/hermetic_cc_toolchain#130]
When trying out this toolchain in our repo which as some Rust code and some Go code I noticed that toolchain can spawn arbitrarily many Zig processes for each Bazel job. This leads to a significant slowdown in the build since there can be hundreds of zig processes fighting for the system resources. 

I was wondering if anybody had a good way to limit the parallelism of the Zig toolchain without affecting the parallelism of other jobs that one might have in their repository?

**Comment by motiejus** [comment]
Prior reading: https://github.com/ziglang/zig/issues/12101

In essence, there shouldn't be a need to arbitrarily throttle them.

**Comment by zdicesare** [comment]
> Prior reading: [ziglang/zig#12101](https://github.com/ziglang/zig/issues/12101)
> 
> In essence, there shouldn't be a need to arbitrarily throttle them.

This underlying issue is still open within the zig project, though I see you resolved it at one point. Could you elaborate on why this issue is resolved within hermetic_cc_toolchain? Have there been changes since to the toolchain, or should bazel be automatically limiting resource consumption of these processes itself such that this is a non-issue?
