### ISSUE TITLE
How does libc caching/cache busting work with zig cc?

### ISSUE THREAD

**Issue by thoughtpolice** [uber/hermetic_cc_toolchain#89]
This isn't so much of an issue as it is a question. Sorry about that.

I'm trying to evaluate if `zig cc` is a good option to use as the cxx toolchain for a [buck2](https://github.com/facebook/buck2) powered build project. There are a lot of attractive properties of `zig cc`, like lots of cross compilation powers. I also do like the fact that it includes a libc, but...

The automated building of libc when you pass something like `zig cc test.c` on first invocation, as well as *recompilation with different options*, makes things really irritating to integrate at first glance. This is actually my major holdup with using it right now. In short:

- the chosen libc is compiled on demand when you first compile something, and
- the chosen libc is *recompiled* when you change certain options, such as `-O2`, which recompiles everything again just for switching one flag!

This is... Obviously not the behavior we want for Bazel or Buck, and especially not when doing Remote Execution with either tool. For those systems, what I want is:

- The first thing to be done, once, in its entirety, so that later stages can depend on the results.
  - So there would be one action to download the toolchain, a second one to "bootstrap" libc in various configurations, and then actual `cxx_library` or `cxx_binary` rules would use both the toolchain and the libc artifacts.
  - This turns libc into an artifact, which is what we want
  - Without that, two different build rules for `a.c` and `b.c` would, in a remote execution context, recompile the entire libc twice! That's a huge waste. (It's sort of like a cache miss, but not really.)
- To avoid the second action entirely
  - i.e. I want to compile libc once with -O2, and reuse that libc with modules *not compiled with -O2*
  - This more accurately reflects how most people expect these libraries to behave; a downstream consumer compiling with slightly different options from upstream does not normally result in transitive recompilation, i.e. it does not result in a cache miss.
    - *Sometimes* you want that. But here, I'm not sure I do. And that can be added to the API of something like `cxx_library`
    - I don't know if this is avoidable, but I'd really like it to be.
  - Realistically every random code generation flag resulting in a cache miss just results in a combinatorial explosion of "toolchains" to support and can severely bloat build time, but I *guess* it's manageable.

So, broadly speaking: how have you handled this? How do you bootstrap libc and then reuse the artifact in downstream rules? Do you just recompile the whole thing on any minor changes to code generation flags? I do know about setting `ZIG_LOCAL_CACHE_DIR`/`ZIG_GLOBAL_CACHE_DIR` which can basically solve 1, but what about 2?

Again, sorry for the question, but I've tried googling this to very little results as `zig cc` is relatively poorly documented, and I'm not really familiar with Bazel; so I'm sort of having to start from scratch here I feel and was wondering if I could get a pointer. Thanks!

**Comment by motiejus** [comment]
> This isn't so much of an issue as it is a question. Sorry about that.
> 
> I'm trying to evaluate if `zig cc` is a good option to use as the cxx toolchain for a [buck2](https://github.com/facebook/buck2) powered build project. There are a lot of attractive properties of `zig cc`, like lots of cross compilation powers. I also do like the fact that it includes a libc, but...
> 
> The automated building of libc when you pass something like `zig cc test.c` on first invocation, as well as _recompilation with different options_, makes things really irritating to integrate at first glance.

Perhaps a nitpick, but an important one: it does not recompile, it compiles anew, keeping the old one, keeping both available for use.

That amortizes the cost of compiling glibc/libcxx to the point where it's not an issue in practice. More on that below.

> This is actually my major holdup with using it right now. In short:
> 
> * the chosen libc is compiled on demand when you first compile something, and
> 
> * the chosen libc is _recompiled_ when you change certain options, such as `-O2`, which recompiles everything again just for switching one flag!
> 
> 
> This is... Obviously not the behavior we want for Bazel or Buck, and especially not when doing Remote Execution with either tool. For those systems, what I want is:
> 
> * The first thing to be done, once, in its entirety, so that later stages can depend on the results.
>   
>   * So there would be one action to download the toolchain, a second one to "bootstrap" libc in various configurations, and then actual `cxx_library` or `cxx_binary` rules would use both the toolchain and the libc artifacts.
>   * This turns libc into an artifact, which is what we want
>   * Without that, two different build rules for `a.c` and `b.c` would, in a remote execution context, recompile the entire libc twice! That's a huge waste. (It's sort of like a cache miss, but not really.)

Can zig cache directories be persistent on the host and reused across invocations? If yes, that may be an option.

zig's cache can be safely shared across parallel zig invocations (we spent a lot of effort to make it performant and safe). This is how our CI workers do it at Uber. We allow-list a directory in `$HOME/.cache` and point Zig to cache it's stubs there.

I agree it is against how Bazel does things — and in mid-2022 it was a huge risk and PITA. But that's what we ended up with: not ideal, but not too costly either.

> 
> * To avoid the second action entirely
>   
>   * i.e. I want to compile libc once with -O2, and reuse that libc with modules _not compiled with -O2_

This sounds fine when we are talking about a "fake" libc like glibc. But the story is different with, say, musl or mingw, where things are statically linked: if you compile your application in Debug mode, you probably want your libc in debug mode too. Or sanitizers. Or `-fomit-frame-pointer`.

> * This more accurately reflects how most people expect these libraries to behave; a downstream consumer compiling with slightly different options from upstream does not normally result in transitive recompilation, i.e. it does not result in a cache miss.
>   
>   * _Sometimes_ you want that. But here, I'm not sure I do. And that can be added to the API of something like `cxx_library`

I agree it may make sense to declare libc targets explicitly. But this is unsupported in Zig, so the conversation should be started there.

Given that, I agree that this should be the ideal state for `hermetic_cc_toolchain`.

>  * I don't know if this is avoidable, but I'd really like it to be.

I don't think it's avoidable right now in Zig, AFAIK it was never an explicit goal. But if you register an issue in Zig about it, please link it from here.

>  * Realistically every random code generation flag resulting in a cache miss just results in a combinatorial explosion of "toolchains" to support and can severely bloat build time, but I _guess_ it's manageable.

In practice at Uber's monorepo we have about a dozen toolchains. Maybe two dozen. And then zig's cache stops growing and all is well.

> So, broadly speaking: how have you handled this? How do you bootstrap libc and then reuse the artifact in downstream rules? Do you just recompile the whole thing on any minor changes to code generation flags? I do know about setting `ZIG_LOCAL_CACHE_DIR`/`ZIG_GLOBAL_CACHE_DIR` which can basically solve 1, but what about 2?

We let Zig freely compile as many toolchains as it needs, because the cost of doing so is miniscule compared to actually building/linking the artifacts and running them.

> Again, sorry for the question, but I've tried googling this to very little results as `zig cc` is relatively poorly documented, and I'm not really familiar with Bazel; so I'm sort of having to start from scratch here I feel and was wondering if I could get a pointer. Thanks!

Keep the questions going!

**Comment by dzbarsky** [comment]
@motiejus Hi, I just stumbled this issue because I'm looking into some non-determinism for my build. I've tracked it down to `external/zig_sdk/tools/<platform_triple>/c++` having a different digest across execution runs. My host platform is a github actions linux runner, but the build is running on RBE.

I haven't looked deeply yet, but I am wondering if we are somehow leaking env or checkout path into this artifact. Any hints that come to mind?

**Comment by motiejus** [comment]
This is shouldn't be the case, let's have a look.

Which OS and zig versions are you using?

Can you reproduce it outside of bazel repository rule? Here is the compile command: https://github.com/uber/hermetic_cc_toolchain/blob/c1860b7d1d62a095020196090fb5d540f8a31388/toolchain/defs.bzl#L174

**Comment by motiejus** [comment]
Ok I am 99% certain stripping the binary will make it reproducible.

I forgot the flag, but it is part of `zig build` command.

**Comment by DavidZbarsky-at** [comment]
Looks like `-fstrip`, I will double-check in a bit if it helps and send a patch

**Comment by motiejus-wix** [comment]
Looks like the original question was answered.
